global:
  scrape_interval: 15s
  scrape_timeout: 15s
  evaluation_interval: 15s

scrape_configs:
    - job_name: "benchmark"
      scrape_interval: 5s
      metrics_path: "/metrics"
      static_configs:
      - targets: ["localhost:2112"]