version: '3.8'

services:

  api:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    restart: always
    container_name: api
    ports:
      - "3003:3003"
    networks:
      - monitor-net

  prometheus:
    image: prom/prometheus:v2.45.0
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention=200h'
      - '--web.enable-lifecycle'
    network_mode: host

  grafana:
    image: grafana/grafana:9.5.6
    user: grafana
    volumes:
      - grafana_data:/var/lib/grafana
    network_mode: host

volumes:
  prometheus_data: {}
  grafana_data: {}

networks:
  monitor-net:
    driver: bridge
